"""empty message

Revision ID: 906610a4258d
Revises: 93f35a0f93cb
Create Date: 2022-01-10 09:08:46.950478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906610a4258d'
down_revision = '93f35a0f93cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lists', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('lists', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=True))
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), onupdate=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    op.drop_column('lists', 'updated_at')
    op.drop_column('lists', 'created_at')
    # ### end Alembic commands ###
