"""empty message

Revision ID: 17ee9b98da10
Revises: cf61e7251d5e
Create Date: 2022-01-10 08:38:16.627012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ee9b98da10'
down_revision = 'cf61e7251d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed_date')
    # ### end Alembic commands ###
