"""empty message

Revision ID: 93f35a0f93cb
Revises: 17ee9b98da10
Create Date: 2022-01-10 08:45:42.941014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93f35a0f93cb'
down_revision = '17ee9b98da10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.sql.func.now()))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(),
                  nullable=True, onupdate=sa.sql.func.now()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
